app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
|
*/

Event::listen('illuminate.query', function($sql)
{
// var_dump($sql);
});


Route::get('/', function () {
    return redirect('/home');
});

Route::get('/home', 'HomeController@index');


// Auth route
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Register
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

Route::controllers(
    [
        'password' => 'Auth\PasswordController',
    ]
    );

Route::resource('projects', 'ProjectsController');
Route::model('projects', 'Project');

Route::bind('projects', function($value, $route) {
    return App\Project::whereSlug($value)->with('projectLead')->first();
});

Route::resource('issues', 'IssuesController');
Route::model('issues', 'Issue');

Route::bind('issues', function($value, $route) {
    return $this->app['Bandit\Repositories\IssuesRepositoryInterface']->getThisIssueWith($value, ['project', 
             'issueType', 
            'createdBy', 
            'assignedTo', 
            'issueStatusType',
            'severityType',
            'priorityType',
            'issueResolutionType']);
});

Route::resource('issues.comments', 'IssueCommentsController');
Route::model('comments', 'Comment');

Route::bind('comments', function($value, $route) {
    return $this->app['Bandit\Repositories\CommentRepositoryInterface']->getThisComment($value);
});


// Admin Area
Route::get('admin', function() {
    return redirect('admin/users');
});


Route::resource('admin/users', 'Admin\UserController');

Route::model('users', 'App\User');
Route::bind('admin/users', function($value, $route) {
  //dd(hello);
  return $this->app['Bandit\Repositories\UserRepositoryInterface']->getUserById($value);
});

Route::resource('admin/workflows', 'Admin\WorkflowController');
Route::model('workflows', 'App\IssueStatusType');

Route::resource('admin/issue_types', 'Admin\IssueTypeController');
Route::model('issue_types', 'App\IssueType');

Route::resource('admin/issue_status_types', 'Admin\IssueStatusTypeController');
Route::model('issue_status_types', 'App\IssueStatusType');

Route::resource('admin/issue_resolution_types', 'Admin\IssueResolutionTypeController');
Route::model('issue_resolution_types', 'App\IssueResolutionType');

Route::resource('admin/status_actions', 'Admin\StatusActionController');
Route::model('status_actions', 'App\StatusAction');

Route::bind('admin/workflows', function($value, $route) {
    //dd($value);
    return \App\IssueStatusType::find($value);
});

Route::get('assets/{id}', 'AssetController@show');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{

    protected $fillable = ['name', 'user_id', 'slug'];
    
    public function projectLead()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function issues()
    {
        return $this->hasMany('App\Issue');
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Http\Requests\CreateProjectRequest;

use App\Project;
use App\Jobs\CreateProjectJob;
use Bandit\Repositories\UserRepositoryInterface;

class ProjectsController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view('projects.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateProjectRequest  $request
     * @return Response
     */
    public function store(CreateProjectRequest $request)
    {
        $this->dispatchFrom(CreateProjectJob::class, $request);

        return redirect()->route('projects.show', [$request->slug]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return Response
     */
    public function show(Project $project)
    {
        $matches = ['project_id' => $project->id, ];
        $issues = \App\Issue::where($matches)->
                              whereNotIn('issue_status_type_id', [5, 3])->
                              with('createdBy', 'assignedTo')->get();
        $issues_archived = \App\Issue::where($matches)->
                              whereIn('issue_status_type_id', [5, 3])->
                              with('createdBy', 'assignedTo')->get();
        return view('projects.show', compact('project', 'issues', 'issues_archived'));  
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return Response
     */
    public function edit(Project $project)
    {
        return view('projects.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  CreateProjectRequest  $request
     * @param  \App\Project  $project
     * @return Response
     */
    public function update(CreateProjectRequest $request, Project $project)
    {
        $this->dispatchFrom(CreateProjectJob::class, $request);

        return redirect()->route('projects.show', [$request->slug]); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return Response
     */
    public function destroy(Project $project)
    {
        //
    }
}

resources/views/projects/create.blade.php
@extends('layouts.master')

@section('content')

<h2>Create New Project</h2>

@include('errors.list')

{!! Form::model(new App\Project, array('route' => ('projects.store'))) !!}
@include('projects.partials._form', array('submitButtonText' => 'Create Project'))
{!! Form::close() !!}

@endsection

resources/views/projects/edit.blade.php
@extends('layouts.master')

@section('content')

<h2>Edit Project</h2>

@include('errors.list')


{!! Form::model($project, 
        ['method' => 'PATCH', 'route' => ['projects.update', $project->slug]]
    ) 
!!}
@include('projects.partials._form', array('submitButtonText' => 'Update Project'))
{!! Form::close() !!}

@endsection

resources/views/projects/index.blade.php
@extends('layouts.master')

@section('content')
<h2>All Projects</h2>
@can ('create', new \App\Project)
<div>
    {!! 
        link_to_route('projects.create', 
                      'Create New Project', 
                      [], 
                      array('class' => '')) 
    !!}
</div>
@endcan

@if ( !$projects->count() )
    You have no projects
@else
    <table class="table">
        <thead>
            <tr>
                <th>Project</th>
                <th>Key</th>
                <th>Project Lead</th>
            </tr>
        </thead>
        <tbody>
        @foreach( $projects as $project ) 
            <tr>
                <td>
                    <a href="{{ route('projects.show', $project->slug) }}">
                        {{ $project->name }}
                    </a>
                </td>
                <td>{{ $project->slug }}</td>
                <td>{{ $project->projectLead->name }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>    
@endif


@endsection

resources/views/projects/show.blade.php
@extends('layouts.master')

@section('content')
<h2>{{ $project->name }}</h2>
<small>
    <strong>KEY: </strong>{{ $project->slug }}
    &nbsp;&nbsp;
    <strong>Lead: </strong>{{ $project->projectLead->name }}
</small>
<br>
@can ('update', $project)
<div>
    <a href="{!! route('projects.edit', array($project->slug)) !!}">
        Edit
    </a>
</div>
@endcan

@can ('create', new \App\Issue)
<div>
    <a href="{!! route('issues.create') !!}">
        Create New Issue
    </a>
</div>
@endcan

<h2>Issues</h2>
<table class="table">
    <thead>
        <tr>
            <th>Issue Key</th>
            <th>Summary</th>
            <th>Asignee</th>
            <th>Reporter</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>
    </thead>
    <tbody>
        @if ( !$issues->count() )
        <tr>
            <td colspan="6">No Issues Logged</td>
        </tr>
        @else
        @foreach( $issues as $issue )
        <tr>
            <td>
                <a href="{{ route('issues.show', $issue->slug)}}">
                    {{ $issue->slug }}
                </a>
            </td>
            <td>{{ $issue->subject }}</td>
            <td>{{ $issue->assignedTo->name }}</td>
            <td>{{ $issue->createdBy->name }}</td>
            <td>{{ $issue->created_at }}</td>
            <td>{{ $issue->updated_at }}</td>
        </tr>
        @endforeach
        @endif
    </tbody>
</table>

<h2>Archived Issues</h2>
<table class="table">
    <thead>
        <tr>
            <th>Issue Key</th>
            <th>Summary</th>
            <th>Asignee</th>
            <th>Reporter</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>
    </thead>
    <tbody>
        @if ( !$issues->count() )
        <tr>
            <td colspan="6">Nothing archived</td>
        </tr>
        @else
        @foreach( $issues_archived as $issue )
        <tr>
            <td>
                <a href="{{ route('issues.show', $issue->slug)}}">
                    {{ $issue->slug }}
                </a>
            </td>
            <td>{{ $issue->subject }}</td>
            <td>{{ $issue->assignedTo->name }}</td>
            <td>{{ $issue->createdBy->name }}</td>
            <td>{{ $issue->created_at }}</td>
            <td>{{ $issue->updated_at }}</td>
        </tr>
        @endforeach
        @endif
    </tbody>
</table>

@endsection